---
application:
  name: "guyamoe"
  project: "nhentai"
  organization: "QoveryCommunity"
  databases:
- type: postgresql
  version: 12
  name: psql
  storage:
  - name: "media"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/media"
routers:
- name: "main-guyamoe"
  routes:
  - application_name: "guyamoe"
    paths:
    - "/*"
